# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation_portuguese', '0003_auto_20160920_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('translation', models.TextField()),
                ('number_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_portuguese.Question')),
            ],
        ),
    ]
