# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_portuguese', '0004_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='negative_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='positive_votes',
            field=models.IntegerField(default=0),
        ),
    ]
