# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_portuguese', '0005_auto_20161001_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='translation',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
